[2024-04-19T19:10:27.054+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-19T19:10:27.083+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.evaluate_model manual__2024-04-19T19:07:23.237464+00:00 [queued]>
[2024-04-19T19:10:27.095+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.evaluate_model manual__2024-04-19T19:07:23.237464+00:00 [queued]>
[2024-04-19T19:10:27.096+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-19T19:10:27.113+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): evaluate_model> on 2024-04-19 19:07:23.237464+00:00
[2024-04-19T19:10:27.124+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=970) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-19T19:10:27.126+0000] {standard_task_runner.py:63} INFO - Started process 986 to run task
[2024-04-19T19:10:27.127+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'evaluate_model', 'manual__2024-04-19T19:07:23.237464+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpbh5y9d5b']
[2024-04-19T19:10:27.128+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask evaluate_model
[2024-04-19T19:10:27.188+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.evaluate_model manual__2024-04-19T19:07:23.237464+00:00 [running]> on host ec31c9b90297
[2024-04-19T19:10:27.302+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='evaluate_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T19:07:23.237464+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T19:07:23.237464+00:00'
[2024-04-19T19:10:27.304+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-19T19:10:27.342+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-19T19:10:27.344+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 59, in evaluate_model
    model = pickle.load(f)
            ^^^^^^^^^^^^^^
io.UnsupportedOperation: read
[2024-04-19T19:10:27.362+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=model_pipeline, task_id=evaluate_model, execution_date=20240419T190723, start_date=20240419T191027, end_date=20240419T191027
[2024-04-19T19:10:27.381+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task evaluate_model (read; 986)
[2024-04-19T19:10:27.424+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-19T19:10:27.446+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-19T19:10:27.448+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
