[2024-04-30T14:07:47.887+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T14:07:47.925+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-30T14:07:30.562365+00:00 [queued]>
[2024-04-30T14:07:47.941+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-30T14:07:30.562365+00:00 [queued]>
[2024-04-30T14:07:47.942+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-30T14:07:47.965+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_quality_check> on 2024-04-30 14:07:30.562365+00:00
[2024-04-30T14:07:47.978+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-30T14:07:47.981+0000] {standard_task_runner.py:63} INFO - Started process 183 to run task
[2024-04-30T14:07:47.982+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'data_quality_check', 'manual__2024-04-30T14:07:30.562365+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpt07ur899']
[2024-04-30T14:07:47.985+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask data_quality_check
[2024-04-30T14:07:48.058+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.data_quality_check manual__2024-04-30T14:07:30.562365+00:00 [running]> on host af5a370a0031
[2024-04-30T14:07:48.201+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T14:07:30.562365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T14:07:30.562365+00:00'
[2024-04-30T14:07:48.203+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T14:07:49.205+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-30T14:07:49.206+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T14:07:49.221+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=data_quality_check, execution_date=20240430T140730, start_date=20240430T140747, end_date=20240430T140749
[2024-04-30T14:07:49.287+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T14:07:49.326+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-30T14:07:49.329+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
