[2024-04-27T20:51:58.451+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T20:51:58.483+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-27T20:51:44.757376+00:00 [queued]>
[2024-04-27T20:51:58.495+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-27T20:51:44.757376+00:00 [queued]>
[2024-04-27T20:51:58.496+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-27T20:51:58.515+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_quality_check> on 2024-04-27 20:51:44.757376+00:00
[2024-04-27T20:51:58.529+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=377) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-27T20:51:58.532+0000] {standard_task_runner.py:63} INFO - Started process 386 to run task
[2024-04-27T20:51:58.533+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'data_quality_check', 'manual__2024-04-27T20:51:44.757376+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpa5k46dko']
[2024-04-27T20:51:58.536+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask data_quality_check
[2024-04-27T20:51:58.610+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.data_quality_check manual__2024-04-27T20:51:44.757376+00:00 [running]> on host c4427bb7f712
[2024-04-27T20:51:58.740+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T20:51:44.757376+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T20:51:44.757376+00:00'
[2024-04-27T20:51:58.743+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T20:51:59.769+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-27T20:51:59.770+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T20:51:59.782+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=data_quality_check, execution_date=20240427T205144, start_date=20240427T205158, end_date=20240427T205159
[2024-04-27T20:51:59.839+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-27T20:51:59.874+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-27T20:51:59.877+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
