[2024-04-23T16:14:19.337+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-23T16:14:19.384+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T16:13:57.006623+00:00 [queued]>
[2024-04-23T16:14:19.405+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T16:13:57.006623+00:00 [queued]>
[2024-04-23T16:14:19.406+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-23T16:14:19.443+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): data_quality_check> on 2024-04-23 16:13:57.006623+00:00
[2024-04-23T16:14:19.467+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-23T16:14:19.470+0000] {standard_task_runner.py:63} INFO - Started process 119 to run task
[2024-04-23T16:14:19.472+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'data_quality_check', 'manual__2024-04-23T16:13:57.006623+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp86gibmoi']
[2024-04-23T16:14:19.475+0000] {standard_task_runner.py:91} INFO - Job 143: Subtask data_quality_check
[2024-04-23T16:14:19.602+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.data_quality_check manual__2024-04-23T16:13:57.006623+00:00 [running]> on host 66b63a6c230d
[2024-04-23T16:14:19.821+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2024-04-23T16:13:57.006623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-23T16:13:57.006623+00:00'
[2024-04-23T16:14:19.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-23T16:14:21.007+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-23T16:14:21.009+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-23T16:14:21.029+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=model_pipeline, task_id=data_quality_check, execution_date=20240423T161357, start_date=20240423T161419, end_date=20240423T161421
[2024-04-23T16:14:21.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-23T16:14:21.176+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-23T16:14:21.179+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
