[2024-04-19T19:03:15.994+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-19T19:03:16.029+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: model_pipeline.train_model manual__2024-04-19T19:03:05.036092+00:00 [queued]>
[2024-04-19T19:03:16.041+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: model_pipeline.train_model manual__2024-04-19T19:03:05.036092+00:00 [queued]>
[2024-04-19T19:03:16.042+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-19T19:03:16.060+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train_model> on 2024-04-19 19:03:05.036092+00:00
[2024-04-19T19:03:16.070+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=815) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-19T19:03:16.073+0000] {standard_task_runner.py:63} INFO - Started process 824 to run task
[2024-04-19T19:03:16.073+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'model_pipeline', 'train_model', 'manual__2024-04-19T19:03:05.036092+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpix77zapn']
[2024-04-19T19:03:16.075+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask train_model
[2024-04-19T19:03:16.142+0000] {task_command.py:426} INFO - Running <TaskInstance: model_pipeline.train_model manual__2024-04-19T19:03:05.036092+00:00 [running]> on host ec31c9b90297
[2024-04-19T19:03:16.267+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='model_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T19:03:05.036092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T19:03:05.036092+00:00'
[2024-04-19T19:03:16.269+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-19T19:06:01.539+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-19T19:06:01.548+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline_dag.py", line 50, in train_model
    with open(os.path.join(parent_directory, 'models', 'model.pkl'), 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/models/model.pkl'
[2024-04-19T19:06:01.569+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=model_pipeline, task_id=train_model, execution_date=20240419T190305, start_date=20240419T190316, end_date=20240419T190601
[2024-04-19T19:06:01.590+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 74 for task train_model ([Errno 2] No such file or directory: '/opt/airflow/dags/models/model.pkl'; 824)
[2024-04-19T19:06:01.663+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-19T19:06:01.699+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-19T19:06:01.702+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
